/**
 * Declares the per-boundary-point GPU buffer layout for game object collision.
 *
 * All boundary sample points for all active game objects are packed into a single
 * flat buffer. Each entry holds the point's position in object-local space.
 * The owning game object is resolved via the boundaryOffset and boundaryCount
 * fields in {@link GameObjectStateSchema}.
 *
 * Boundary points are generated by {@link ColliderGenerator} from whatever
 * {@link Collider} component is attached — PixelBodyCollider, BoxCollider, or
 * CircleCollider — and are uploaded once on spawn or rebuilt on collider dirty.
 *
 * Consumed by {@link GameObjectBuffers} (buffer sizing) and {@link ShaderFactory}
 * (WGSL struct generation).
 */
export class GameObjectColliderSchema {
    public static readonly fields = [
        ['localX', 'i32'],
        ['localY', 'i32'],
    ] as const satisfies ReadonlyArray<readonly [string, string]>;

    /** Number of 32-bit words per GameObjectBoundaryPoint entry. */
    public static readonly stride = GameObjectColliderSchema.fields.length;

    /** Byte size of one GameObjectBoundaryPoint entry. */
    public static readonly byteStride = GameObjectColliderSchema.stride * 4;

    /** Returns the GameObjectBoundaryPointSchema fields. @internal */
    public static GetFields() { return GameObjectColliderSchema.fields; }
}
