import type { PixelBodyCollider } from '../../../component/definitions/collider/pixelbodycollider/PixelBodyCollider';

import { ComponentField } from '../ComponentField';

export class PixelBodyColliderField extends ComponentField<PixelBodyCollider> {
    public static readonly forType = 'PixelBodyCollider';
    public static readonly menu = 'Physics/'

    // No fields for this, automatically generated by the PixelBody component.
    protected BuildFields(container: HTMLElement): void { }
}